### ISSUE TITLE
Use of crypto.randomUUID restricts library usage to secure contexts (HTTPS)

### ISSUE THREAD

**Issue by tmac12** [omnedia/ngx-connection-beam#1]
The library uses `crypto.randomUUID` to generate unique component IDs. However, crypto.randomUUID is only available in secure contexts, such as HTTPS connections. 
This restricts the library's usage in the following scenarios:

- Applications running over HTTP (e.g., in local development environments).
- Contexts that do not support HTTPS or where HTTPS is not required.

See crypto.randomUUI [documentation](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID) 

**Steps to Reproduce**:
Use the library in a non-secure context (e.g., on a page served over HTTP).
Observe that crypto.randomUUID is unavailable, causing an error or malfunction in the ID generation process.

**Expected Behavior**: 
The library should function correctly even in non-secure contexts. It would be helpful to implement a fallback solution for ID generation when crypto.randomUUID is not available, such as using an alternative based on Math.random() or a polyfill.

**Comment by xSentry** [comment]
I will look into alternatives.
Probably swapping to a UUID Library then.
